### ISSUE TITLE
`ClusterOrder` vs `Clustering<OPTICSModel>` in OPTICS

### ISSUE THREAD

**Issue by DiTo97** [elki-project/elki#106]
Why does the abstract OPTICS base class  ([`AbstractOPTICS`](https://github.com/elki-project/elki/blob/master/elki-clustering/src/main/java/elki/clustering/optics/AbstractOPTICS.java)) and most OPTICS implementations (e.g., [`FastOPTICS`](https://github.com/elki-project/elki/blob/master/elki-clustering/src/main/java/elki/clustering/optics/FastOPTICS.java)) available in the library return a `ClusterOrder` object, whereas the [`OPTICSXi`](https://github.com/elki-project/elki/blob/master/elki-clustering/src/main/java/elki/clustering/optics/OPTICSXi.java) implementation returns a `Clustering<OPTICSModel>` object?

IIUC, the former is just the reachability ordering that OPTICS generates, whereas the latter applies the Xi algorithm and predecessor correction to extract clusters (and noise) from said ordering. Then, how can I compare the two output modalities?

**N.B.:** When I say _compare_, I don't mean an algorithm to compare two clustering ouputs (i.e., Rand measure), but how to programmatically compare the two output modalities given those different object types in the code.

**Comment by kno10** [comment]
You can use `OPTICSXi` with `FastOPTICS`, too.

`-algorithm clustering.optics.OPTICSXi -opticsxi.algorithm FastOPTICS`

So either you apply the Xi extraction both times, or neither.

`OPTICSHeap`/`OPTICSList` are two implementations of the standard OPTICS algorithm with different data structures (heap vs. list). The cluster order results of these two may differ due to equal reachability distances.

**Comment by DiTo97** [comment]
Thank you @kno10,

This is exactly the kind of information that I was looking for. I am closing the issue!
