### ISSUE TITLE
ArrayModifiableIntegerDBIDs.java has protected constructors

### ISSUE THREAD

**Issue by saideepakb** [elki-project/elki#28]
Hi,

Is `ArrayModifiableIntegerDBIDs` supposed to be a non-public class with protected constructors? If yes, then how do we instantiate a new object of this class?

https://github.com/elki-project/elki/blob/master/elki-core-dbids-int/src/main/java/de/lmu/ifi/dbs/elki/database/ids/integer/ArrayModifiableIntegerDBIDs.java

Thanks,
Deepak

cc: @anam282

**Comment by kno10** [comment]
Yes, this is intentional.

The entire package is not meant to be used directly, but only through the interfaces.

This is stated clearly in the package documentation:

https://elki-project.github.io/releases/current/doc/de/lmu/ifi/dbs/elki/database/ids/integer/package-summary.html
https://github.com/elki-project/elki/blob/master/elki-core-dbids-int/src/main/java/de/lmu/ifi/dbs/elki/database/ids/integer/package-info.java

> Integer-based DBID implementation -- do not use directly - always use DBIDUtil.

**Comment by anam282** [comment]
Thanks @kno10
