### ISSUE TITLE
Anderberg Hierarchical clustering - maximum array size reached

### ISSUE THREAD

**Issue by dkajtoch** [elki-project/elki#72]
I am trying to run hierarchical clustering with around 170k vectors of size 768 each and ELKI throws the message
```
This implementation does not scale to data sets larger than 65536 instances (~16 GB RAM), at which point the Java maximum array size is reached.
```
my code looks like this:
```bash
java -cp "src/dependency/*:src/elki/*" de.lmu.ifi.dbs.elki.application.KDDCLIApplication -dbc.in input.tsv -algorithm clustering.hierarchical.AnderbergHierarchicalClustering
```

**Comment by kno10** [comment]
This algorithm *requires* a **quadratic** distance matrix. It uses a linearized memory layout of the upper triangular matrix.
Java arrays are limited in size to 2^31 instances, hence the maximum data set size supported is 65536.

Do the math: 170k instances, that is 170000*169999/2*8 bytes = 107 GB RAM.
The runtime will be similarly bad.

You need to sample your data. If you really need to process the entire data this way (and you do have enough RAM), you really need to implement this yourself. You will also want to parallelize the distance matrix computation, too. Because the runtime also goes up quadratic (worst case: cubic) with data set size.

**Closing as won't fix.** The algorithm is quadratic, it will not scale to large data.

**Comment by dkajtoch** [comment]
Alright, thanks @kno10!
